= lexica
Mariell Hoversholm <mariell@mardroemmar.dev>
v1.0, 2022-01-02
:current-version: 0.1.0

A library for common maps and mapping tasks.

== Usage

=== Repository

To depend on a release, you need only depend on the official Maven central, or a mirror thereof.
If you're using Maven, this is automatic.
Gradle users must:

.build.gradle.kts
[source,kotlin]
----
repositories {
    mavenCentral()
}
----

To depend on a `SNAPSHOT` version, you need to depend on the Sonatype snapshot repository:

.pom.xml
[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss-snapshot</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----

.build.gradle.kts
[source,kotlin]
----
repositories {
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}
----

=== Artifact

The dependency may be declared as follows:

.pom.xml
[source,xml,subs="+attributes"]
----
<dependencies>
  <dependency>
    <groupId>dev.mardroemmar</groupId>
    <artifactId>lexica</artifactId>
    <version>{current-version}</version>
  </dependency>
</dependencies>
----

.build.gradle.kts
[source,kotlin,subs="+attributes"]
----
dependencies {
    implementation("dev.mardroemmar:lexica:{current-version}")
    // or `api`, `testImplementation`, `compile` (deprecated), `shadow`, etc.
}
----

=== Java

This project currently uses Java 11. The project has a policy of supporting at least the 2 newest long-term-support (LTS) versions of Java: any older versions are always subject to be removed in a MAJOR version bump.
This means that e.g. version `1.0.0` with Java 11 will never drop Java 11, but rather bump to `2.0.0` first.

== Licence

This project is licensed under the link:https://choosealicense.com/licenses/mpl-2.0/[Mozilla Public Licence 2.0].
Because of this, the project is freely distributable and usable, both by proprietary and free (as in libre) software.
You need not ask for permission to use the project in any way; all usages are welcome within the terms of the licence.
